company_name: "STD international Co.,LTD"
short_name: "STD international"
business_reg: "GCN ĐKKD số 0105364332 do sở Kế hoạch và Đầu tư Hà Nội cấp ngày 11/06/2011"
address: "Tòa nhà H8, Ngõ 80 Trung Kính, P. Yên Hòa, Q. Cầu Giấy, TP Hà Nội, Việt Nam."
phone: "024 3992 6488"
email: "info@stdpharma.vn"
